### ISSUE TITLE
Gmail SMTP port

### ISSUE THREAD

**Issue by tedr56** [julianlam/nodebb-plugin-emailer-local#2]
Not really an issue but for some reason, gmail smtp refuse 465 port with the plugin.
`warn: [emailer.smtp] Unable to send`reset`email to uid 11!!`

The alternative is using 587 port
`info: [emailer.smtp] Sent`reset`email to uid 11`

**Comment by julianlam** [comment]
Migrated here: NodeBB/nodebb-plugin-emailer-local#6
