### ISSUE TITLE
Oudated ?

### ISSUE THREAD

**Issue by Miaourt** [julianlam/nodebb-plugin-emailer-local#6]
warn: [plugins/nodebb-plugin-emailer-local] "callbacked" deprecated as of 0.4x. Use asynchronous method instead for hook: filter:admin.header.build

:x dunno what is mean... but i think this could be cool for the plugin to use the "async" thing ?

**Comment by Fusselwurm** [comment]
this repo seems abandoned, see https://github.com/NodeBB/nodebb-plugin-emailer-local

**Comment by flipflopsimsommer** [comment]
this information should be in the readme or somewhere!!

**Comment by Fusselwurm** [comment]
/summon @julianlam people still seem to arrive here and get confused. 

could you remove this repo or put a link into the README or so?

**Comment by flipflopsimsommer** [comment]
@Fusselwurm do you know if the [NodeBB/nodebb-plugin-emailer-local](https://github.com/Nodebb/nodebb-plugin-emailer-local) repo is still supported?
- it has no issue page.
- it is searching for a main maintainer but the link to it's threat is dead.

the **npm** `nodebb-plugin-emailer-local`  links to this projekt

is [erlgo/nodebb-plugin-emailer-ssl-smtp](https://github.com/erlgo/nodebb-plugin-emailer-ssl-smtp) still supported?

but it looks outdated too.

**Comment by julianlam** [comment]
@flipflopsimsommer Thank you for the nudge. For all those arriving here:

## [This is the official repository package](https://github.com/NodeBB/nodebb-plugin-emailer-local)

We _were_ waiting on the original author to grant us access, although the plugin has now been unpublished, so we have re-published it under the proper ownership/repository:

https://www.npmjs.com/package/nodebb-plugin-emailer-local
