### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by thanhhungtn1** [julianlam/nodebb-plugin-emailer-local#8]
Since Nodebb v0.5 this plugin not works anymore. Just showing 404 error

**Comment by Fusselwurm** [comment]
@thanhhungtn1 see https://github.com/NodeBB/nodebb-plugin-emailer-local

**Comment by thanhhungtn1** [comment]
@Fusselwurm  thank you, but it's not working with gmail smtp, isn't it?

**Comment by Fusselwurm** [comment]
@thanhhungtn1 no idea – i've been using it only with a local mailer w/o authentication.

**Comment by thanhhungtn1** [comment]
@Fusselwurm oh, thank you. I'm kinda lazy to install new local email server :smile: Thank you again.

**Comment by ghost** [comment]
The NodeBB owned code at the previous link also stopped working. This worked for me today: https://github.com/ainesophaur/nodebb-plugin-emailer-local

**Comment by julianlam** [comment]
If the fork works, great! :smile: 

Alternatively, you can use this one: https://github.com/NodeBB/nodebb-plugin-emailer-local
